#!/usr/bin/env bash
# Nginx server to listen on port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# start service
service nginx start
kill "$(pgrep 'nginx' | head -1)"
