#!/usr/bin/env bash
# script that loops from 1 to 10 and displays bad luck good luck best school

a=10
while [ $a -lt 20 ]
do
	if [ $a -eq 13 ]
	then
		echo "bad luck"
	elif [ $a -eq 17 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( a++ ))
done
